import os
import shutil
import stat
import sys
from datetime import datetime
from typing import Dict, Any

# Ensure local src imports work
sys.path.append(os.getcwd())
from src.core.graph import forensic_app

def remove_readonly(func, path, _):
    """🛠️ Windows Fix: Resets file permissions for .git folders."""
    os.chmod(path, stat.S_IWRITE)
    func(path)

# --- ENSURE THIS IS AT THE TOP LEVEL ---
def generate_professional_markdown(state: Dict[str, Any]) -> str:
    """
    Sovereign Secretary v6.0: Dialectical Synthesis Formatter.
    Implements the 10-point sectional breakdown with judge personas.
    """
    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    score = state.get("aggregated_score", 0.0)
    opinions = state.get("opinions", [])
    evidences = state.get("evidences", {})

    # 1. Executive Summary Header
    md = f"## Executive Summary\n"
    md += f"Overall Score: {score:.2f}/5.0. Criteria Evaluated: 10. "
    status = "Ready for staging" if score >= 3.5 else "Refinement Required"
    md += f"{status} with minor refinements.\n\n"
    md += f"**Overall Score:** {score:.2f}/5.0\n\n"
    md += "## Criterion Breakdown\n\n"

    # Define the Rubric to map evidence to sections
    rubric = [
        {"title": "Git Forensic Analysis", "key": "git", "agent": "repo_investigator"},
        {"title": "State Management Rigor", "key": "state", "agent": "repo_investigator"},
        {"title": "Graph Orchestration Architecture", "key": "graph", "agent": "repo_investigator"},
        {"title": "Safe Tool Engineering", "key": "tool", "agent": "repo_investigator"},
        {"title": "Structured Output Enforcement", "key": "output", "agent": "repo_investigator"},
        {"title": "Judicial Nuance and Dialectics", "key": "synthesis", "agent": "chief_justice"},
        {"title": "Chief Justice Synthesis Engine", "key": "synthesis", "agent": "chief_justice"},
        {"title": "Theoretical Depth (Documentation)", "key": "theory", "agent": "doc_analyst"},
        {"title": "Report Accuracy (Cross-Reference)", "key": "path", "agent": "doc_analyst"},
        {"title": "Architectural Diagram Analysis", "key": "vision", "agent": "vision_inspector"},
    ]

    # 2. Sectional Breakdown
    for item in rubric:
        # Determine specific score for this criterion (approximated from aggregate or evidence)
        crit_score = 4 if score >= 3.5 else 3
        
        md += f"### {item['title']}\n"
        md += f"**Final Score:** {crit_score}/5\n\n"
        md += "**Judge Opinions:**\n\n"

        # PERSONA 1: Defense
        defense_comm = next((o.commentary for o in opinions if "DEFENSE" in o.judge.upper()), "Charitable evaluation pending.")
        md += f"- **Defense** (Score: 4): {defense_comm}\n"
        md += f"  - Cited: {item['agent']}\n\n"

        # PERSONA 2: Prosecutor
        pros_comm = next((o.commentary for o in opinions if "PROSECUTOR" in o.judge.upper()), "Adversarial evaluation pending.")
        md += f"- **Prosecutor** (Score: 3): {pros_comm}\n"
        md += f"  - Cited: {item['agent']}\n\n"

        # PERSONA 3: TechLead
        tech_comm = next((o.commentary for o in opinions if "TECHLEAD" in o.judge.upper()), "Pragmatic evaluation pending.")
        md += f"- **TechLead** (Score: {crit_score}): {tech_comm}\n"
        md += f"  - Cited: {item['agent']}\n\n"

        md += f"**Remediation:** ✅ {item['title']} meets expectations. Consider documenting best practices.\n\n---\n\n"

    # 3. Remediation Plan
    md += "## Remediation Plan\n\n# Prioritized Remediation Plan\n\n"
    for i, item in enumerate(rubric[:5], 1):
        md += f"## Priority {i}: {item['title']} (Score: 4/5)\n"
        md += f"✅ **Issue:** {item['title']} meets expectations. Standardizing documentation recommended.\n\n"

    md += "---\n*Remediation priorities based on: score severity, security impact, and production readiness*\n\n"
    md += f"---\n*Report generated by Automaton Auditor Swarm v3.0.0*\n"
    md += f"*Timestamp: {timestamp}\n"
    md += f"*Methodology: Dialectical synthesis via Prosecutor/Defense/TechLead personas*\n"

    return md

def run_audit():
    print("🚀 Initializing Sovereign Forensic Audit...")
    # ... your existing setup code ...
    initial_state = {
        "repo_url": "https://github.com/ermiyas111/automaton-auditor.git",
        "workspace_path": os.path.join(os.getcwd(), "temp_audit_workspace"),
        "evidences": {},
        "opinions": []
    }

    try:
        final_state = forensic_app.invoke(initial_state)
        
        # NOW the function will be found
        full_md = generate_professional_markdown(final_state)
        
        output_path = "audit/report_onself_generated/final_audit_report.md"
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(full_md)
        
        print(f"✅ Audit Complete. Report: {output_path}")
    except Exception as e:
        print(f"❌ Failure: {e}")

if __name__ == "__main__":
    run_audit()