import datetime
from src.core.state import ForensicState

def generate_final_report(state: ForensicState):
    """🎯 FINAL NODE: Transforms state data into a professional Markdown Audit."""
    evidences = state.get("refined_evidences", [])
    opinions = state.get("opinions", [])
    metadata = state.get("metadata")
    
    avg_score = sum(o.score for o in opinions) / len(opinions) if opinions else 0.0
    status = "✅ ACCEPTED" if avg_score >= 3.0 else "❌ REJECTED"
    
    report = f"""# ⚖️ Forensic Swarm Audit Report
**Timestamp:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Verdict:** {status} ({avg_score:.2f}/5)

---

## 🕵️ Forensic Evidence Ledger
| # | Status | Artifact/Goal | Source | Technical Rationale |
| :--- | :---: | :--- | :--- | :--- |
"""
    for i, e in enumerate(evidences, 1):
        icon = "✅" if e.found else "❌"
        report += f"| {i} | {icon} | {e.goal} | {e.location} | {e.rationale} |\n"

    report += """
---

## ⚖️ Judicial Opinions Summary
| Judge | Score | Key Argument |
| :--- | :---: | :--- |
"""
    for op in opinions:
        report += f"| {op.judge} | {op.score}/5 | {op.argument[:120]}... |\n"

    report += f"""
---

## 📊 Project Metadata
- **Commits:** {len(metadata.git_log)}
- **Uv Lock:** {"Verified" if metadata.has_uv_lock else "Not Found"}

*Report generated by Gemini-Powered Forensic Swarm.*
"""
    return {"final_report": report}